artifact_uri: ./automl_result/1/b1573faa269c4e2bbfe4099c7e7bcfda/artifacts
end_time: 1621582664257
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: b1573faa269c4e2bbfe4099c7e7bcfda
run_uuid: b1573faa269c4e2bbfe4099c7e7bcfda
source_name: ''
source_type: 4
source_version: ''
start_time: 1621582606524
status: 3
tags: []
user_id: liug28
