artifact_uri: ./automl_result/1/eaea27cc005442409ceed90ac6f4154e/artifacts
end_time: 1621582606517
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: eaea27cc005442409ceed90ac6f4154e
run_uuid: eaea27cc005442409ceed90ac6f4154e
source_name: ''
source_type: 4
source_version: ''
start_time: 1621582386924
status: 3
tags: []
user_id: liug28
