artifact_uri: ./automl_result/1/9bfa349a091f4bf69cde2f18fec9b4bb/artifacts
end_time: 1621641295790
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 9bfa349a091f4bf69cde2f18fec9b4bb
run_uuid: 9bfa349a091f4bf69cde2f18fec9b4bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1621641230197
status: 3
tags: []
user_id: liug28
