artifact_uri: ./automl_result/1/c134f5231da0445e85db44ba58efab4c/artifacts
end_time: 1621088807851
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: c134f5231da0445e85db44ba58efab4c
run_uuid: c134f5231da0445e85db44ba58efab4c
source_name: ''
source_type: 4
source_version: ''
start_time: 1621044205785
status: 3
tags: []
user_id: liug28
