artifact_uri: ./automl_result/1/a6e33d1535004c17adc89c8b3dbc77aa/artifacts
end_time: 1621088879023
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: a6e33d1535004c17adc89c8b3dbc77aa
run_uuid: a6e33d1535004c17adc89c8b3dbc77aa
source_name: ''
source_type: 4
source_version: ''
start_time: 1621088807858
status: 3
tags: []
user_id: liug28
