artifact_uri: ./automl_result/1/0d0fb9714ea9407689bb68b8c6aa7fbf/artifacts
end_time: 1621044161201
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 0d0fb9714ea9407689bb68b8c6aa7fbf
run_uuid: 0d0fb9714ea9407689bb68b8c6aa7fbf
source_name: ''
source_type: 4
source_version: ''
start_time: 1621044113557
status: 3
tags: []
user_id: liug28
