artifact_uri: ./automl_result/1/1d6d012bfc584ad1990e1845b1ca6d1d/artifacts
end_time: 1621641062388
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 1d6d012bfc584ad1990e1845b1ca6d1d
run_uuid: 1d6d012bfc584ad1990e1845b1ca6d1d
source_name: ''
source_type: 4
source_version: ''
start_time: 1621641018144
status: 3
tags: []
user_id: liug28
